"""
Interactive End-to-End Demo Script showing full P4 <-> P5 Contract Integration
including Area (m^2), Perimeter (m), GIS Polygonization, and Roof Material Classification.

Generates a clean 3-panel visual output PNG (Original Image, AI Mask, Overlay).
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Headless backend
import matplotlib.pyplot as plt
import rasterio

from contracts.tile_contract import TileContract
from cv.inference.engine import RealSegmentationEngine
from cv.models.roof_classifier import RoofClassifier
from preprocessing.polygonization.vectorizer import FeatureVectorizer


def create_color_mask(predicted_mask: np.ndarray) -> np.ndarray:
    """
    Converts uint8 predicted mask {0, 1, 2, 3} into an RGB color image.
    0 = BACKGROUND (Dark Gray: [40, 40, 40])
    1 = BUILDING   (Red: [230, 50, 50])
    2 = ROAD       (Yellow: [240, 200, 40])
    3 = WATERBODY  (Blue: [40, 120, 240])
    """
    h, w = predicted_mask.shape
    color_mask = np.zeros((h, w, 3), dtype=np.uint8)

    color_mask[predicted_mask == 0] = [40, 40, 40]    # Background
    color_mask[predicted_mask == 1] = [230, 50, 50]   # Building (Red)
    color_mask[predicted_mask == 2] = [240, 200, 40]  # Road (Yellow)
    color_mask[predicted_mask == 3] = [40, 120, 240]  # Waterbody (Blue)

    return color_mask


def load_real_geotiff_tile():
    """
    Reads a 512x512 tile crop from sample_data/test1.png or sample_drone_ortho.tif using rasterio/PIL.
    """
    sample_tif = os.path.join("sample_data", "test1.png")
    if not os.path.exists(sample_tif):
        sample_tif = os.path.join("sample_data", "sample_drone_ortho.tif")

    if sample_tif.endswith(".tif"):
        with rasterio.open(sample_tif) as src:
            win = rasterio.windows.Window(256, 256, 512, 512)
            data = src.read([1, 2, 3], window=win)
            return np.transpose(data, (1, 2, 0)), src.transform
    else:
        from PIL import Image
        img = Image.open(sample_tif).convert("RGB").resize((512, 512))
        return np.array(img, dtype=np.uint8), None


def run_manual_test():
    print("=" * 70)
    print("   DRISHTI GeoAI -- P4 AI INFERENCE & P5 GIS AREA/PERIMETER DEMO")
    print("=" * 70)

    # 1. P5 CREATES TILE & EXTRACTS TILE DATA
    print("\n[PHASE 1: P5 DATA PREPROCESSING & TILING]")
    print("  P5 opening drone orthophoto image and slicing a 512x512 tile...")
    
    tile = TileContract(
        tile_id="tile_demo_001",
        image_id="sample_drone_ortho",
        job_id="job_sih_2026",
        x_offset=256,
        y_offset=256,
        width=512,
        height=512,
    )

    tile_data, affine_transform = load_real_geotiff_tile()

    print("  [OK] TileContract generated by P5")
    print(f"       Tile ID : {tile.tile_id} | Dimensions: {tile.width}x{tile.height}")
    print(f"       Raster Data Shape: {tile_data.shape} (RGB uint8)")

    # 2. P5 HANDS OVER TO P4 CV/ML INFERENCE
    print("\n[PHASE 2: HANDOFF TO P4 CV/ML AI LAYER]")
    print("  Passing TileContract + tile_data to P4 RealSegmentationEngine...")

    p4_engine = RealSegmentationEngine()
    segmentation_result = p4_engine.predict(tile, tile_data)

    print("  [OK] P4 completed inference and returned SegmentationContract!")

    # 3. P5 VECTORIZATION: AREA & PERIMETER CALCULATION
    print("\n[PHASE 3: P5 GIS VECTORIZATION & AREA/PERIMETER CALCULATION]")
    print("  P5 FeatureVectorizer polygonizing predicted masks into FeatureContracts...")

    vectorizer = FeatureVectorizer(resolution_m=0.5)  # 0.5m/pixel resolution
    features = vectorizer.polygonize(segmentation_result, affine_transform=affine_transform)

    print(f"  [OK] Successfully extracted {len(features)} spatial GIS features!")
    print("\n  Sample Extracted GIS Feature Contracts:")
    for f in features[:5]:
        print(f"    • Feature ID     : {f.feature_id}")
        print(f"      Type           : {f.feature_type.value}")
        print(f"      Calculated Area: {f.area_m2:>8.2f} m^2")
        print(f"      Perimeter      : {f.perimeter_m:>8.2f} m")
        print(f"      Centroid (x,y) : ({f.centroid['coordinates'][0]:.2f}, {f.centroid['coordinates'][1]:.2f})")
        print(f"      Confidence     : {f.confidence * 100:.1f}% ({f.confidence_level.value})")
        print(f"      Status         : {f.status.value}")
        print("-" * 50)

    # 4. OPTIONAL ROOF MATERIAL CLASSIFICATION
    print("\n[PHASE 4: OPTIONAL ROOF MATERIAL CLASSIFICATION]")
    building_pixels = (segmentation_result.predicted_mask == 1)
    if np.any(building_pixels):
        building_crop = tile_data[100:200, 100:200]
        roof_classifier = RoofClassifier()
        roof_result = roof_classifier.predict(building_crop)

        print("  [OK] RoofClassifier finished classification:")
        print(f"       • Detected Roof Material : {roof_result['roof_type']}")
        print(f"       • Confidence Score       : {roof_result['confidence'] * 100:.1f}%")

    # 5. RENDER CLEAN 3-PANEL VISUAL OUTPUT PLOT (NO HEATMAPS)
    print("\n[PHASE 5: RENDERING CLEAN 3-PANEL VISUAL OUTPUT]")
    color_mask = create_color_mask(segmentation_result.predicted_mask)
    overlay = (0.5 * tile_data + 0.5 * color_mask).astype(np.uint8)

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle("Drishti GeoAI -- P4 AI Segmentation & P5 GIS Feature Extraction", fontsize=16, fontweight='bold')

    axes[0].imshow(tile_data)
    axes[0].set_title("1. Original Drone Photo (Input)", fontsize=13, fontweight='bold')
    axes[0].axis("off")

    axes[1].imshow(color_mask)
    axes[1].set_title("2. AI Predicted Mask\n(Red=Building, Yellow=Road, Blue=Water)", fontsize=13, fontweight='bold')
    axes[1].axis("off")

    axes[2].imshow(overlay)
    axes[2].set_title("3. Mask Overlay on Drone Photo", fontsize=13, fontweight='bold')
    axes[2].axis("off")

    plt.tight_layout()
    output_png = "p4_p5_demo_clean_output.png"
    plt.savefig(output_png, dpi=150, bbox_inches='tight')
    plt.close()

    print(f"  [SUCCESS] Clean 3-panel visual output saved to: {os.path.abspath(output_png)}")

    print("\n" + "=" * 70)
    print("  [OK] ALL DEMO PHASES PASSED -- P4 AI & P5 GIS Vectorizer complete!")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    run_manual_test()
