/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFeaturesIndexRouteImport } from './routes/_app/features/index'
import { Route as AppFeaturesFeatureIdRouteImport } from './routes/_app/features/$featureId'
import { Route as AppImagesIndexRouteImport } from './routes/_app/images/index'
import { Route as AppImagesImageIdRouteImport } from './routes/_app/images/$imageId'
import { Route as AppImagesUploadRouteImport } from './routes/_app/images/upload'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesIndexRoute = AppFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesFeatureIdRoute = AppFeaturesFeatureIdRouteImport.update({
  id: '/features/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesIndexRoute = AppImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesImageIdRoute = AppImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesUploadRoute = AppImagesUploadRouteImport.update({
  id: '/images/upload',
  path: '/images/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/exports': typeof AppExportsRoute
  '/map': typeof AppMapRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/features/$featureId': typeof AppFeaturesFeatureIdRoute
  '/images/$imageId': typeof AppImagesImageIdRoute
  '/images/upload': typeof AppImagesUploadRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/features/': typeof AppFeaturesIndexRoute
  '/images/': typeof AppImagesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/exports': typeof AppExportsRoute
  '/map': typeof AppMapRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/features/$featureId': typeof AppFeaturesFeatureIdRoute
  '/images/$imageId': typeof AppImagesImageIdRoute
  '/images/upload': typeof AppImagesUploadRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/features': typeof AppFeaturesIndexRoute
  '/images': typeof AppImagesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/map': typeof AppMapRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/features/$featureId': typeof AppFeaturesFeatureIdRoute
  '/_app/images/$imageId': typeof AppImagesImageIdRoute
  '/_app/images/upload': typeof AppImagesUploadRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/features/': typeof AppFeaturesIndexRoute
  '/_app/images/': typeof AppImagesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/exports'
    | '/map'
    | '/review'
    | '/settings'
    | '/features/$featureId'
    | '/images/$imageId'
    | '/images/upload'
    | '/jobs/$jobId'
    | '/features/'
    | '/images/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/exports'
    | '/map'
    | '/review'
    | '/settings'
    | '/'
    | '/features/$featureId'
    | '/images/$imageId'
    | '/images/upload'
    | '/jobs/$jobId'
    | '/features'
    | '/images'
    | '/jobs'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/exports'
    | '/_app/map'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/'
    | '/_app/features/$featureId'
    | '/_app/images/$imageId'
    | '/_app/images/upload'
    | '/_app/jobs/$jobId'
    | '/_app/features/'
    | '/_app/images/'
    | '/_app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features/': {
      id: '/_app/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof AppFeaturesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features/$featureId': {
      id: '/_app/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof AppFeaturesFeatureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images/': {
      id: '/_app/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof AppImagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images/$imageId': {
      id: '/_app/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof AppImagesImageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images/upload': {
      id: '/_app/images/upload'
      path: '/images/upload'
      fullPath: '/images/upload'
      preLoaderRoute: typeof AppImagesUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppExportsRoute: typeof AppExportsRoute
  AppMapRoute: typeof AppMapRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFeaturesFeatureIdRoute: typeof AppFeaturesFeatureIdRoute
  AppImagesImageIdRoute: typeof AppImagesImageIdRoute
  AppImagesUploadRoute: typeof AppImagesUploadRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppFeaturesIndexRoute: typeof AppFeaturesIndexRoute
  AppImagesIndexRoute: typeof AppImagesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppExportsRoute: AppExportsRoute,
  AppMapRoute: AppMapRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFeaturesFeatureIdRoute: AppFeaturesFeatureIdRoute,
  AppImagesImageIdRoute: AppImagesImageIdRoute,
  AppImagesUploadRoute: AppImagesUploadRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppFeaturesIndexRoute: AppFeaturesIndexRoute,
  AppImagesIndexRoute: AppImagesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
